name: state_provider
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  flutter:
    sdk: flutter

dev_dependencies:
  custom_lint: ^0.6.4
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  riverpod_generator: ^2.4.2
  riverpod_lint: ^2.3.12

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
